<?php
/**
 * ****************************************************************************
 * ModuleInstaller - MODULE FOR XOOPS
 * Copyright (c) Michael Beck (mamba)
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * @copyright       Michael Beck (mamba)
 * @license         http://www.gnu.org/licenses/gpl-2.0.html GNU Public License
 * @package         moduleinstaller
 * @author 			Michael Beck (mamba)
 *
 * Version : $Id:
 * ****************************************************************************
 */

if (!defined('XOOPS_ROOT_PATH')) {
    die('XOOPS root path not defined');
}

$moduleDirName = basename( dirname( __FILE__ ) ) ;

$modversion['name'] = _MI_INSTALLER_NAME;
$modversion['version'] = '1.0';
$modversion['description'] = _MI_INSTALLER_DESC;
$modversion['author'] = 'Michael Beck';
$modversion['nickname'] = 'Mamba';
$modversion['help'] = 'page=help';
$modversion['license'] = 'GNU GPL 2.0';
$modversion['license_url'] = "www.gnu.org/licenses/gpl-2.0.html/";
$modversion['official'] = 0;
$modversion['image'] = 'images/logo_moduleInstaller.png';
$modversion['dirname'] = 'moduleinstaller';
$modversion['dirmoduleadmin'] = '/Frameworks/moduleclasses/moduleadmin';
$modversion['icons16'] = '../../Frameworks/moduleclasses/icons/16';
$modversion['icons32'] = '../../Frameworks/moduleclasses/icons/32';

//about
$modversion['release_date']     = '2011/07/20';
$modversion["module_website_url"] = "www.xoops.org/";
$modversion["module_website_name"] = "XOOPS";
$modversion["module_status"] = "RC 1";
$modversion['min_php']='5.2';
$modversion['min_xoops']="2.5";
$modversion['min_admin']='1.1';

// SQL Tables
// $modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
// $modversion['tables'][0] = 'installer';

// Admin menu
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';
$modversion['hasMain'] = 0;
// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Search
$modversion['hasSearch'] = 0;

// Smarty
$modversion['use_smarty'] = 1;
